### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by SKempin** [ndchristie/vueport#1]
```
C:\vueport\build\plugins.js:8
    acc[key] = !isNaN(parseFloat(value)) ? value : `"${value.toString()}"`;
                                                            ^

TypeError: Cannot read property 'toString' of undefined
    at keys.reduce (C:\vueport\build\plugins.js:8:61)
    at Array.reduce (native)
    at mapEnvVariables (C:\vueport\build\plugins.js:6:4)
    at Object.<anonymous> (C:\vueport\build\plugins.js:14:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\vueport\build\webpack.config.js:2:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by ndchristie** [comment]
This is a result of not having a .env file present with the necessary keys.  I'm marking it as a bug, but would also remark that this project is still in its earliest phases, and many essential features are still being mapped out.
